// <auto-generated />
using System;
using CS_Discord_Bot.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CS_Discord_Bot.Migrations
{
    [DbContext(typeof(DiscordMusicDBContext))]
    [Migration("20250205142719_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CS_Discord_Bot.Models.Guild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Anchor")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("DiscordId")
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("Discord_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id")
                        .HasName("PK__Guild__3213E83FA17C45A2");

                    b.ToTable("Guild", (string)null);
                });

            modelBuilder.Entity("CS_Discord_Bot.Models.GuildPlaylist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GuildId")
                        .HasColumnType("int")
                        .HasColumnName("guild_id");

                    b.Property<int>("PlaylistId")
                        .HasColumnType("int")
                        .HasColumnName("playlist_id");

                    b.HasKey("Id")
                        .HasName("PK__GuildPla__3213E83FB4C15C0A");

                    b.HasIndex("GuildId");

                    b.HasIndex("PlaylistId");

                    b.ToTable("GuildPlaylist", (string)null);
                });

            modelBuilder.Entity("CS_Discord_Bot.Models.Playlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AuthorId")
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("Author_id");

                    b.Property<DateOnly>("CreationDate")
                        .HasColumnType("date")
                        .HasColumnName("Creation_date");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit")
                        .HasColumnName("Is_public");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id")
                        .HasName("PK__Playlist__3213E83F9A148AA8");

                    b.ToTable("Playlist", (string)null);
                });

            modelBuilder.Entity("CS_Discord_Bot.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasDefaultValue("NN")
                        .HasColumnName("Author_name");

                    b.Property<double?>("Duration")
                        .HasColumnType("float");

                    b.Property<string>("FilePath")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)")
                        .HasColumnName("File_path");

                    b.Property<string>("Link")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id")
                        .HasName("PK__Song__3213E83F33BB9D15");

                    b.ToTable("Song", (string)null);
                });

            modelBuilder.Entity("CS_Discord_Bot.Models.SongPlaylist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PlaylistId")
                        .HasColumnType("int")
                        .HasColumnName("playlist_id");

                    b.Property<int>("SongId")
                        .HasColumnType("int")
                        .HasColumnName("song_id");

                    b.HasKey("Id")
                        .HasName("PK__SongPlay__3213E83FA68EB569");

                    b.HasIndex("PlaylistId");

                    b.HasIndex("SongId");

                    b.ToTable("SongPlaylist", (string)null);
                });

            modelBuilder.Entity("CS_Discord_Bot.Models.GuildPlaylist", b =>
                {
                    b.HasOne("CS_Discord_Bot.Models.Guild", "Guild")
                        .WithMany("GuildPlaylists")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__GuildPlay__guild__4316F928");

                    b.HasOne("CS_Discord_Bot.Models.Playlist", "Playlist")
                        .WithMany("GuildPlaylists")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__GuildPlay__playl__440B1D61");

                    b.Navigation("Guild");

                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("CS_Discord_Bot.Models.SongPlaylist", b =>
                {
                    b.HasOne("CS_Discord_Bot.Models.Playlist", "Playlist")
                        .WithMany("SongPlaylists")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__SongPlayl__playl__403A8C7D");

                    b.HasOne("CS_Discord_Bot.Models.Song", "Song")
                        .WithMany("SongPlaylists")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__SongPlayl__song___3F466844");

                    b.Navigation("Playlist");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("CS_Discord_Bot.Models.Guild", b =>
                {
                    b.Navigation("GuildPlaylists");
                });

            modelBuilder.Entity("CS_Discord_Bot.Models.Playlist", b =>
                {
                    b.Navigation("GuildPlaylists");

                    b.Navigation("SongPlaylists");
                });

            modelBuilder.Entity("CS_Discord_Bot.Models.Song", b =>
                {
                    b.Navigation("SongPlaylists");
                });
#pragma warning restore 612, 618
        }
    }
}
